#!/bin/bash
DIR="$(cd "$(dirname "$0")" && pwd)"
coffee="$DIR/../node_modules/.bin/coffee"
source_dir="$DIR/../source"
build_dir="$DIR/../build"
spec_dir="$DIR/../spec"
bin_dir="$DIR/../bin"
support_dir="$DIR/../support"
docs_dir="$DIR/../docs"
npm_dir="$DIR/.."

clean() {
  clean-build-dir
  clean-spec-dir
}

clean-build-dir() {
  rm -f $build_dir/**/*.js $build_dir/**/*.map
}

clean-spec-dir() {
  rm -rf $spec_dir/**/*.spec.coffee
}

build() {
  build-source
  build-readme
  build-specs
}

build-source() {
  $coffee -cmb -o $build_dir $source_dir
}

build-readme() {
  cat $docs_dir/JasmineCoffee.coffee.md > $npm_dir/README.md
  echo -e "\n--------------------------------------------------------------------------------\n" >> $npm_dir/README.md
  cat $npm_dir/LICENSE.md >> $npm_dir/README.md
}

build-specs() {
  $coffee $support_dir/build-specs.coffee "docs/**/*.coffee.md"
}

argv=("$*")
for arg in $argv; do eval ${arg}; done
